
name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == 'Approved' }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            issue_id: ${{ github.event.issue.number }}
            payload_marker: target_payload 
        
  deploy-dev:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
     # - name: Download workflow artifact
     #   uses: benday-inc/download-artifact@main
     #   with:
     #      token: ${{ secrets.GITHUB_TOKEN }}
     #      repository_owner: 'n3wt0n'
     #      repository_name: 'DeploymentApprovals'
     #      workflow_name: 'CI'
     #      run_id: ${{ needs.parse.outputs.ci-run-id }}
     #      download_path: '${{ github.workspace }}'
     #      download_filename: 'your-artifact-name.zip'
           
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: 'CI'
          repo: 'DeploymentApprovals'
          run_number: ${{ needs.parse.outputs.ci-run-number }}
          name: 'your-artifact-name'
          path: '${{ github.workspace }}'
          
      - name: Deploy to DEV
        run: echo Simulating Deployment     
          
      - uses: JasonEtco/create-an-issue@v2
        name: Create approval Issue for Prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: Prod
          RUNID: ${{ needs.parse.outputs.ci-run-id }}
        with:
          filename: .github/deployment-approval.md
  
  deploy-prod:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Prod' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download workflow artifact
        uses: benday-inc/download-artifact@main
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           repository_owner: 'n3wt0n'
           repository_name: 'DeploymentApprovals'
           workflow_name: 'CI'
           run_id: ${{ needs.parse.outputs.ci-run-id }}
           download_path: '${{ github.workspace }}'
           download_filename: 'your-artifact-name.zip'

      - name: Deploy to PROD
        run: echo Simulating Deployment
        
  close-issue:
    if: ${{ always() }}
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    
    steps:
      - name: Close Issue
        if: ${{ needs.deploy-dev.result == 'success' || needs.deploy-prod.result == 'success' }}
        uses: peter-evans/close-issue@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # repository: # optional, default is ${{ github.repository }}
          # issue-number: # optional, default is ${{ github.event.issue.number }}          
          comment: 'Deployment Completed 🌟'
