
name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == 'Approved' }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
    steps:
      - name: Get Issue data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            issue_id: ${{ github.event.issue.number }}
            payload_marker: target_payload

      - name: Print Values
        run: |
          echo "RunID: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runId }}
          echo "Environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      
        
  deploy-dev:
    needs: [parse]
    if: ${{ needs.parse.outputs.deploy-environment == 'Dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
